language: android
android:
  components:
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository 
    - build-tools-28.0.1
    - android-26
  licenses:
    - '.+'